import { chromium } from "playwright";
const BASE = "http://localhost:3001";
const b = await chromium.launch({ args: ["--use-gl=angle","--use-angle=swiftshader","--ignore-gpu-blocklist"] });
const p = await b.newPage({ viewport: { width: 1280, height: 800 } });
const errs = [], dyn = [];
p.on("pageerror", e => errs.push(String(e.message)));
p.on("console", m => { if (m.type()==="error") errs.push(m.text()); });
p.on("request", r => { if (r.url().includes("dynamic")) dyn.push(r.url()); });
await p.goto(BASE, { waitUntil: "networkidle" });
await p.waitForTimeout(3000);
const demoPicker = await p.getByTestId("connect-wallet").count();
const html = await p.content();
const mentionsDynamic = /dynamic/i.test(html);
const dynEls = await p.locator('[data-testid^="dynamic"], iframe[src*="dynamic"], #dynamic-widget, [class*="dynamic" i]').count();
console.log("demo picker (connect-wallet testid) count:", demoPicker, "(expect 0 when Dynamic active)");
console.log("Dynamic network requests:", dyn.length);
console.log("Dynamic DOM elements:", dynEls);
console.log("HTML mentions 'dynamic':", mentionsDynamic);
await p.screenshot({ path: "/tmp/thermal-dynamic.png" });
console.log("console errors:", errs.length ? errs.slice(0,8) : "none");
await b.close();
